const mongoose = require('mongoose');

const resumeSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  title: {
    type: String,
    default: 'Untitled Resume',
    trim: true,
  },
  template: {
    type: String,
    enum: ['modern', 'classic', 'minimal', 'bold', 'professional', 'creative', 'custom-ai'],
    default: 'modern',
  },
  customTemplateHtml: { // Store the raw Handlebars/Tailwind markup generated by Gemini
    type: String,
    default: ''
  },
  sectionOrder: {
    type: [String],
    default: ['profile', 'experience', 'education', 'skills', 'projects'],
  },
  profile: {
    fullName: { type: String, default: '' },
    jobTitle: { type: String, default: '' },
    email: { type: String, default: '' },
    phone: { type: String, default: '' },
    linkedin: { type: String, default: '' },
    github: { type: String, default: '' },
    summary: { type: String, default: '' },
    photoUrl: { type: String, default: '' },
  },
  experience: [{
    id: { type: String, required: true },
    role: { type: String, default: '' },
    company: { type: String, default: '' },
    startDate: { type: String, default: '' },
    endDate: { type: String, default: '' },
    location: { type: String, default: '' },
    current: { type: Boolean, default: false },
    bullets: [{ type: String }],
  }],
  education: [{
    id: { type: String, required: true },
    degree: { type: String, default: '' },
    school: { type: String, default: '' },
    startDate: { type: String, default: '' },
    endDate: { type: String, default: '' },
    gpa: { type: String, default: '' },
    description: { type: String, default: '' },
  }],
  skills: [{
    type: String,
    trim: true,
  }],
  projects: [{
    id: { type: String, required: true },
    name: { type: String, default: '' },
    description: { type: String, default: '' },
    technologies: { type: String, default: '' },
    link: { type: String, default: '' },
  }],
  customSections: [{
    id: { type: String, required: true },
    title: { type: String, default: 'Custom Section' },
    content: { type: String, default: '' },
  }],
  atsScore: {
    type: Number,
    default: 0,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

resumeSchema.pre('save', function (next) {
  this.updatedAt = Date.now();
  next();
});

resumeSchema.pre('findOneAndUpdate', function (next) {
  this.set({ updatedAt: Date.now() });
  next();
});

module.exports = mongoose.model('Resume', resumeSchema);
